# Generated by Django 5.2.5 on 2025-10-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='questions',
        ),
    ]
