# Generated by Django 5.2.5 on 2025-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_content_question_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
    ]
