# Generated by Django 5.2.5 on 2025-10-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_topic_total_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='total_videos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
