# Generated by Django 5.2.5 on 2025-11-05 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
