# Generated by Django 5.2.5 on 2025-11-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_emailverification_last_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
