# Generated by Django 5.2.8 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_options_alter_user_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
